### ISSUE TITLE
Exchange: BITFINEX

### ISSUE THREAD

**Issue by gmanroney** [gmanroney/cryptoboard#2]
https://docs.bitfinex.com/docs

{
      "name": "bitfinex",
      "docurl": "https://docs.bitfinex.com/docs",
      "wssurl": "wss://api.bitfinex.com/ws",
      "pairs": "BTCUSD, LTCUSD, LTCBTC, ETHUSD, ETHBTC, ETCUSD, ETCBTC, BFXUSD, BFXBTC, RRTUSD, RRTBTC, ZECUSD, ZECBTC",
      "active": "Y"
}

**Comment by gmanroney** [comment]
Basic function working but it crashes after a minute with the following error:

BITFINEX wss://api.bitfinex.com/ws BTCUSD
BITFINEX wss://api.bitfinex.com/ws LTCUSD
BITFINEX wss://api.bitfinex.com/ws LTCBTC
BITFINEX wss://api.bitfinex.com/ws ETHUSD
BITFINEX wss://api.bitfinex.com/ws ETHBTC
BITFINEX wss://api.bitfinex.com/ws ETCUSD
BITFINEX wss://api.bitfinex.com/ws ETCBTC
BITFINEX wss://api.bitfinex.com/ws BFXUSD
BITFINEX wss://api.bitfinex.com/ws BFXBTC
BITFINEX wss://api.bitfinex.com/ws RRTUSD
BITFINEX wss://api.bitfinex.com/ws RRTBTC
BITFINEX wss://api.bitfinex.com/ws ZECUSD
BITFINEX wss://api.bitfinex.com/ws ZECBTC
Finshed launch
Connected to Redis Server
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: unexpected server response (429)
    at ClientRequest._req.on (/Users/germoroney/Development/cryptoboard/node_modules/ws/lib/WebSocket.js:653:21)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by gmanroney** [comment]
Going to mark this as DONE and raise a bug separately. It does work and this intermittent problem is not yet entirely replicable. However it is mentioned in another git project relating to bitfinex and their own API. May be worth further investigation -> https://github.com/bitfinexcom/bitfinex-api-node
